[[plugins]]
repo = 'Shougo/ddu.vim'
hook_add = '''
  nnoremap <Plug>(ff-buffers)             <Cmd>Ddu buffer<CR>
  nnoremap <Plug>(ff-files)               <Cmd>Ddu files<CR>
  nnoremap <Plug>(ff-resume)              <Cmd>Ddu resume<CR>
  nnoremap <Plug>(ff-config_files)        <Cmd>Ddu config_file<CR>
  nnoremap <Plug>(ff-help_tags)           <Cmd>Ddu help_tag<CR>
  nnoremap <Plug>(ff-grep_help)           <Cmd>Ddu grep_help<CR>
  nnoremap <Plug>(ff-grep)                <Cmd>Ddu rg<CR>
  nnoremap <Plug>(ff-lines)               <Cmd>Ddu line<CR>
  nnoremap <Plug>(ff-lsp_implementations) <Cmd>Ddu lsp_implementation<CR>
  nnoremap <Plug>(ff-lsp_references)      <Cmd>Ddu lsp_reference<CR>
  nnoremap <Plug>(lsp-codeAction)         <Cmd>Ddu lsp_codeAction<CR>
  nnoremap <Plug>(ff-mrw)                 <Cmd>Ddu mrw<CR>

  nnoremap <Plug>(git-status)             <Cmd>Ddu git_status<CR>
  nnoremap <Plug>(git-branch)             <Cmd>Ddu git_branch<CR>

  AlterCmd fp Ddu<Space>plugin
  AlterCmd fq Ddu<Space>ghq
'''

[[plugins]]
repo = 'shun/ddu-source-buffer'

[[plugins]]
repo = 'Shougo/ddu-kind-file'

[[plugins]]
repo = 'Shougo/ddu-ui-ff'

[[plugins]]
repo = 'yuki-yano/ddu-filter-fzf'

[[plugins]]
repo = 'matsui54/ddu-source-file_external'

[[plugins]]
repo = 'uga-rosa/ddu-source-lsp'

[[plugins]]
repo = 'uga-rosa/ddu-filter-converter_devicon'

[[plugins]]
repo = 'matsui54/ddu-source-help'

[[plugins]]
repo = 'shun/ddu-source-rg'

[[plugins]]
repo = 'Shougo/ddu-source-line'

[[plugins]]
repo = 'Shougo/ddu-filter-matcher_substring'

[[plugins]]
repo = 'matsui54/ddu-vim-ui-select'
lazy = true
lua_add = '''
  vim.ui.select = function(...)
    vim.fn['dein#source'] 'ddu-vim-ui-select'
    vim.ui.select(...)
  end
'''

[[plugins]]
repo = 'kuuote/ddu-source-mr'

[[plugins]]
repo = 'Shougo/ddu-source-action'

[[plugins]]
repo = 'kyoh86/ddu-filter-converter_hl_dir'

[[plugins]]
repo = 'Shougo/ddu-column-filename'

[[plugins]]
repo = 'kuuote/ddu-source-git_status'

[[plugins]]
repo = 'kyoh86/ddu-source-git_branch'

[[plugins]]
repo = 'KentoOgata/ddu-kind-git_repo'

[[plugins]]
repo = 'kyoh86/ddu-source-git_log'
