# denops製のGitクライアント
# 良いところを上手く説明できない Chaperonは競合解決するときに便利
[[plugins]]
repo = 'lambdalisue/gin.vim'
depends = 'denops.vim'
hook_add = '''
  nnoremap <Plug>(git-commit) <Cmd>Gin commit -v<CR>
  nnoremap <Plug>(git-commit:amend) <Cmd>Gin commit -v --amend<CR>
  nnoremap <Plug>(git-log:all) <Cmd>GinLog --all<CR>
  nnoremap <Plug>(git-log:current) <Cmd>GinLog -- %:p<CR>

  let g:gin_log_default_args = [
        \ '--graph',
        \ '--pretty=oneline',
        \ '--abbrev-commit',
        \ '--max-count=100',
        \ '--decorate=short',
        \ ]

  AlterCmd gs GinStatus
  AlterCmd gb GinBranch
  lua vim.cmd.AlterCmd { 'gp', 'Gin push' }
  lua vim.cmd.AlterCmd { 'gpf', 'Gin push --force-with-lease --force-if-include' }
  lua vim.cmd.AlterCmd { 'gpu', [[exec 'Gin' 'push' '--set-upstream' 'origin' system('git branch --show-current')]] }

  " bufferlineするときにリストにあるとだいたいパースできなくて死ぬので
  autocmd VimRc FileType gin* setl nobuflisted
'''
[plugins.ftplugin]
gin-branch = '''
  nnoremap <buffer> N <Plug>(gin-action-new)
'''

# 現在編集しているバッファーについて、git関連の操作や表示を提供する。
# 動作が軽快で、Visualで選択した範囲をstageしたりできるのでかなり便利
[[plugins]]
repo = 'lewis6991/gitsigns.nvim'
on_event = ['BufReadPost', 'BufNewFile']
hook_add = '''
  set signcolumn=yes
'''
hooks_file = '$DEIN_CONFIG_DIR/gitsigns.lua'

[[plugins]]
repo = 'KentoOgata/committia.vim'
on_path = ['COMMIT_EDITMSG', 'MERGE_MSG']
hook_add = '''
  let g:committia_open_only_vim_starting = 0
'''
