# denops製のGitクライアント
# 良いところを上手く説明できない Chaperonは競合解決するときに便利
[[plugins]]
repo = 'lambdalisue/gin.vim'
depends = 'denops.vim'
hook_add = '''
  nnoremap <Plug>(git-commit) <Cmd>Gin commit -v<CR>
  nnoremap <Plug>(git-commit:amend) <Cmd>Gin commit -v --amend<CR>
  nnoremap <Plug>(git-log:current) <Cmd>GinLog<CR>
  nnoremap <Plug>(git-log:all) <Cmd>GinLog --all<CR>
  nnoremap <Plug>(git-log:cbuf) <Cmd>GinLog --follow -- %:p<CR>

  let g:gin_log_persistent_args = [
        \ '++emojify',
        \ '--graph',
        \ '--format=%C(green)%h%C(reset) %s %C(bold yellow)%cr%C(reset) %C(bold magenta)<%an>%C(reset) %C(auto)%d%C(reset)',
        \ '--abbrev-commit',
        \ '--max-count=100',
        \ ]

  AlterCmd gb GinBranch
  lua vim.cmd.AlterCmd { 'gp', 'Gin push' }
  lua vim.cmd.AlterCmd { 'gpf', 'Gin push --force-with-lease --force-if-include' }
  lua vim.cmd.AlterCmd { 'gpu', [[exec 'Gin' 'push' '--set-upstream' 'origin' system('git branch --show-current')]] }

  " bufferlineするときにリストにあるとだいたいパースできなくて死ぬので
  autocmd VimRc FileType gin* setl nobuflisted
'''
[plugins.ftplugin]
gin = '''
  lua << EOF
  if package.loaded['nvim-treesitter'] ~= nil then
    vim.treesitter.start(vim.api.nvim_get_current_buf(), 'unifieddiff')
  end
EOF
'''
gin-diff = '''
  lua << EOF
  if package.loaded['nvim-treesitter'] ~= nil then
    vim.treesitter.start(vim.api.nvim_get_current_buf(), 'unifieddiff')
  end
EOF
'''
'''
gin-branch = '''
  nnoremap <buffer> N <Plug>(gin-action-new)
'''

# 現在編集しているバッファーについて、git関連の操作や表示を提供する。
# 動作が軽快で、Visualで選択した範囲をstageしたりできるのでかなり便利
[[plugins]]
repo = 'lewis6991/gitsigns.nvim'
on_event = ['BufReadPost', 'BufNewFile']
hook_add = '''
  set signcolumn=yes
'''
hooks_file = '$DEIN_CONFIG_DIR/gitsigns.lua'

[[plugins]]
repo = 'rhysd/committia.vim'
on_path = ['COMMIT_EDITMSG', 'MERGE_MSG']
hook_add = '''
  let g:committia_open_only_vim_starting = 0
'''

[[plugins]]
repo = 'NeogitOrg/neogit'
on_cmd = 'Neogit'
depends = 'plenary.nvim'
lua_add = '''
  vim.cmd.AlterCmd {
    'gs',
    'exec "Neogit" "cwd="..gin#util#worktree(bufname())'
  }
'''
lua_source = '''
  require('neogit').setup {
    integrations = {
      telescope = false,
      diffview = true,
      fzf_lua = true,
    }
  }
'''

[[plugins]]
repo = 'sindrets/diffview.nvim'
on_cmd = 'DiffviewOpen'
