[[plugins]]
repo = 'nvim-telescope/telescope.nvim'
on_lua = 'telescope'
on_cmd = 'Telescope'
hook_add = '''
  AlterCmd t Telescope

  function! g:MapTelescope() abort
    nnoremap <Plug>(ff-files) <Cmd>Telescope find_files<CR>
    nnoremap <Plug>(ff-config_files) <Cmd>exec 'Telescope' 'find_files' 'cwd='..gin#util#worktree(bufname())<CR>
  endfunction
  if $NVIM_FF ==# 'telescope'
    call MapTelescope()
  endif
'''
lua_source = '''
  require('telescope').setup {
    defaults = {
      layout_strategy = 'flex',
      layout_config = {
        prompt_position = 'top',
      },
      sorting_strategy = 'ascending',
      border = true,
      borderchars = { '─', '│', '─', '│', '┌', '┐', '┘', '└' },
    },
    extensions = {
      fzf = {
        fuzzy = true,
        override_generic_sorter = true,
        override_file_sorter = true,
        case_mode = 'smart_case',
      }
    }
  }
  require('telescope').load_extension 'fzf'
'''

[[plugins]]
repo = 'nvim-telescope/telescope-fzf-native.nvim'
build = 'make'
