[[plugins]]
repo = 'Shougo/shougo-s-github'
name = 'Shougo'
if = false

[[plugins]]
repo = 'thinca/config'
name = 'thinca'
if = false

[[plugins]]
repo = 'monaqa/dotfiles'
name = 'monaqa'
if = false

[[plugins]]
repo = 'kuuote/dotvim'
name = 'kuuote'
if = false

[[plugins]]
repo = 'yutkat/dotfiles'
name = 'yutkat'
if = false

[[plugins]]
repo = 'yuki-yano/dotfiles'
name = 'yuki-yano'
if = false

[[plugins]]
repo = '4513ECHO/dotfiles'
name = '4513ECHO'
if = false

[[plugins]]
repo = 'kyoh86/dotfiles'
name = 'kyoh86'
if = false

[[plugins]]
repo = 'rebelot/dotfiles'
name = 'rebelot'
if = false

[[plugins]]
repo = 'lambdalisue/dotfiles'
name = 'lambdalisue'
if = false

[[plugins]]
repo = 'L3MON4D3/Dotfiles'
name = 'L3MON4D3'
if = false

[[plugins]]
repo = 'eihigh/dotfiles'
name = 'eihigh'
if = false

[[plugins]]
repo = 'cohama/.vim'
name = 'cohama'
if = false

[[plugins]]
repo = 'uga-rosa/dotfiles'
name = 'uga-rosa'
if = false

[[plugins]]
repo = 'folke/dot'
name = 'folke'
if = false

[[plugins]]
repo = 'yasunori0418/dotfiles'
name = 'yasunori0418'
if = false
