[[plugins]]
repo = 'Shougo/dein.vim'
hook_add = '''
autocmd VimRc FileType toml autocmd BufWinEnter <buffer> call dein#toml#syntax()

call dein#options(#{
\   auto_recache: v:true,
\ })
'''

[[plugins]]
repo = 'editorconfig/editorconfig-vim'

[[plugins]]
repo = 'vim-jp/vimdoc-ja'
merged = false
hook_add = '''
set helplang=ja,en
'''

[[plugins]]
repo = 'vim-denops/denops.vim'

[[plugins]]
repo = 'cocopon/iceberg.vim'

[[plugins]]
repo = 'catppuccin/vim'
name = 'catppuccin'

[[plugins]]
repo = 'lambdalisue/gin.vim'
hook_add = '''
nmap <space>aa <Cmd>GinStatus<CR>
nmap <space>ab <Cmd>GinBranch<CR>
'''

# vim:foldmarker=def\ ,enddef foldmethod=marker foldenable foldlevel=0
