[for]
prefix = ["for", "for-const"]
body = """
for (const ${2:element} of ${1:array}) {
\t$0
}
"""

["import denoland"]
prefix = 'import-denoland'
body = """
import { ${5:imports} } from "https://deno.land/${1|x,std|}/${2:mod}@${3:version}/${4:path}";
"""

["unpack object"]
prefix = 'unpack object'
body = """
const { $0 } = $1;
"""

["unpack tuple"]
prefix = 'unpack tuple'
body = """
const [$0] = $1;
"""
