[repro]
prefix = "repro"
if = "base"
body = """
let &rtp = \\$VIMRUNTIME
const s:packpath = expand('<script>:p:h')
let &packpath = s:packpath
const s:ToPackPath = { name -> s:packpath .. '/pack/github.com/opt/' .. name }

function s:PackAdd(ghrepo) abort
\tconst plugin = #{
\t\t\\ path: s:ToPackPath(a:ghrepo),
\t\t\\ repo: \\$'https://github.com/{a:ghrepo}.git',
\t\t\\ name: a:ghrepo,
\t\t\\ }
\tif !isdirectory(plugin.path)
\t\tcall system(['git', 'clone', plugin.repo, plugin.path])
\tendif
\texec 'packadd' plugin.name
endfunction

call s:PackAdd($0)
"""


